### PR TITLE
Properly Link existing Image files

### PR DESCRIPTION
**Pull request by dartajax**
I also attempted to fix the table of contents a little bit too.

### CODE REVIEW

**Comment by saschaben** [comment]
this looks good to merge

**Comment by dartajax** [comment]
I would love to merge this but appear to have some conflicts I need to resolve first.

**Comment by stopfstedt** [comment]
^ handling it.

**Comment by stopfstedt** [comment]
oh boy. there are about 20 merge conflicts.

@dartajax - should I just take yours as-is?

**Comment by dartajax** [comment]
Can we just use my version (the version I pushed up there) as is?

**Comment by dartajax** [comment]
I made all these changes on my local frontend\user-guide and did a git push directly so i am going to close this pull request and the issue it references #4

**Pull request closed without merging**
